### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by laetitia-tureau** [laetitia-tureau/computer-database#8]
- [x] Aucune logique dans le modèle donc le modèle ne lève pas d'exceptions 
         - utiliser des validators ?
         - logique dans les services ?
- [x] Requête avec jointure pour récupérer une liste de computers associés aux companies (left join)
- Récupérer la connexion dans chaque méthode (puis la fermer)

**Comment by laetitia-tureau** [comment]
- [x] returner un Optional au lieu d'un null
- [x] les noms de variables doivent faire au minimim 3 caractères
- privilégier les hasNext() aux next() pour un ResultSet
- utiliser les List plutôt que les ArrayList
- respecter cohérence dans les models => builder pour tous les modèles ou pour aucun

**Comment by laetitia-tureau** [comment]
- [x] enlever les redondances dans la cli et utiliser les enumérations
- [x] faire un mapper pour transformer un string en timestamp

**Comment by laetitia-tureau** [comment]
- [x] update date computer

**Comment by laetitia-tureau** [comment]
- [x] mappers : classe permettant de mapper un objet (ResultSet) vers un autre objet (company, computer) à partir d'une requête
- [x] ouvrir et fermer la connexion à la BD dans chaque DAO et implémenter close() dans MysqlConnection (utiliser pattern singleton)
